### ISSUE TITLE
ZIP-Issue

### ISSUE THREAD

**Issue by atze007** [auino/cookidump#1]
Hey, 
I get the following message: 

```
Traceback (most recent call last):
  File "cookidump.py", line 155, in <module>
    shutil.make_archive(OUTPUTFILE, 'zip', TMPDIR)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 582, in make_archive
    filename = func(base_name, base_dir, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 484, in _make_zipfile
    zf.write(path, path)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/zipfile.py", line 1148, in write
    self._writecheck(zinfo)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/zipfile.py", line 1114, in _writecheck
    " would require ZIP64 extensions")
zipfile.LargeZipFile: Filesize would require ZIP64 extensions
```

**Comment by auino** [comment]
Solved in the new version.
